=begin
#Phone.com API

#This is a Phone.com api PhoneCom definition

OpenAPI spec version: 1.0.0
Contact: apisupport@phone.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
PhoneCom Codegen version: 2.4.4

=end

require 'spec_helper'
require 'json'

# Unit tests for PhoneComClient::CallerIdsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CallerIdsApi' do
  before do
    # run before each test
    @instance = PhoneComClient::CallerIdsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallerIdsApi' do
    it 'should create an instance of CallerIdsApi' do
      expect(@instance).to be_instance_of(PhoneComClient::CallerIdsApi)
    end
  end

  # unit tests for get_caller_ids
  # Show the Caller ID options a given extension can use.
  # Show the Caller ID options a given extension can use. See Intro to Caller IDs for more on the properties.
  # @param account_id Account ID
  # @param extension_id Extension ID
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :filters_number Number filter
  # @option opts [Array<String>] :filters_name Name filter
  # @option opts [String] :sort_number Number sorting
  # @option opts [String] :sort_name Name sorting
  # @option opts [Integer] :limit Max results
  # @option opts [Integer] :offset Results to skip
  # @option opts [String] :fields Field set
  # @return [ListCallerIds]
  describe 'get_caller_ids test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
