=begin
#Phone.com API

#This is a Phone.com api PhoneCom definition

OpenAPI spec version: 1.0.0
Contact: apisupport@phone.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
PhoneCom Codegen version: 2.4.4

=end

require 'spec_helper'
require 'json'

# Unit tests for PhoneComClient::ContactsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ContactsApi' do
  before do
    # run before each test
    @instance = PhoneComClient::ContactsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactsApi' do
    it 'should create an instance of ContactsApi' do
      expect(@instance).to be_instance_of(PhoneComClient::ContactsApi)
    end
  end

  # unit tests for create_account_extension_contact
  # Add a new address book contact for an extension.
  # Add a new address book contact for an extension. See Account Contacts for more info on the fields in each item.
  # @param account_id Account ID
  # @param extension_id Extension ID
  # @param [Hash] opts the optional parameters
  # @option opts [CreateContactParams] :data Contact data
  # @return [ContactFull]
  describe 'create_account_extension_contact test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_account_extension_contact
  # Delete a contact from the address book.
  # Delete a contact from the address book. See Account Contacts for more info on the fields in each item.
  # @param account_id Account ID
  # @param extension_id Extension ID
  # @param contact_id Contact ID
  # @param [Hash] opts the optional parameters
  # @return [DeleteEntry]
  describe 'delete_account_extension_contact test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_account_extension_contact
  # Retrieve the details of an address book contact.
  # Retrieve the details of an address book contact. See Account Contacts for more info on the fields in each item.
  # @param account_id Account ID
  # @param extension_id Extension ID
  # @param contact_id Contact ID
  # @param [Hash] opts the optional parameters
  # @return [ContactFull]
  describe 'get_account_extension_contact test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_account_extension_contacts
  # Show the Caller ID options a given extension can use.
  # Show the Caller ID options a given extension can use. See Intro to Caller IDs for more on the properties.
  # @param account_id Account ID
  # @param extension_id Extension ID
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :filters_id ID filter
  # @option opts [Array<String>] :filters_group_id Group filter
  # @option opts [Array<String>] :filters_updated_at Updated At filter
  # @option opts [String] :sort_id ID sorting
  # @option opts [String] :sort_updated_at Updated At sorting
  # @option opts [Integer] :limit Max results
  # @option opts [Integer] :offset Results to skip
  # @option opts [String] :fields Field set
  # @return [ListContacts]
  describe 'list_account_extension_contacts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replace_account_extension_contact
  # Update the info of a contact in the address book.
  # Update the info of a contact in the address book. See Account Contacts for more info on the fields in each item.
  # @param account_id Account ID
  # @param extension_id Extension ID
  # @param contact_id Contact ID
  # @param [Hash] opts the optional parameters
  # @option opts [CreateContactParams] :data Contact data
  # @return [ContactFull]
  describe 'replace_account_extension_contact test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
