=begin
#Phone.com API

#This is a Phone.com api PhoneCom definition

OpenAPI spec version: 1.0.0
Contact: apisupport@phone.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
PhoneCom Codegen version: 2.4.4

=end

require 'spec_helper'
require 'json'

# Unit tests for PhoneComClient::ExpressServiceCodesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExpressServiceCodesApi' do
  before do
    # run before each test
    @instance = PhoneComClient::ExpressServiceCodesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExpressServiceCodesApi' do
    it 'should create an instance of ExpressServiceCodesApi' do
      expect(@instance).to be_instance_of(PhoneComClient::ExpressServiceCodesApi)
    end
  end

  # unit tests for get_account_express_srv_code
  # Show details of an account Express Service Code
  # This service shows the details of an Account Express Service Code.
  # @param account_id Account ID
  # @param code_id Device ID
  # @param [Hash] opts the optional parameters
  # @return [ExpressServiceCodeFull]
  describe 'get_account_express_srv_code test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_account_express_srv_codes
  # Get the Express Service Code associated with your account in list format.
  # Get the Express Service Code associated with your account in list format. See Express Service Codes for more detail.
  # @param account_id Account ID
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :filters_id ID filter
  # @return [ListExpressServiceCodes]
  describe 'list_account_express_srv_codes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
