=begin
#Phone.com API

#This is a Phone.com api PhoneCom definition

OpenAPI spec version: 1.0.0
Contact: apisupport@phone.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
PhoneCom Codegen version: 2.4.4

=end

require 'spec_helper'
require 'json'

# Unit tests for PhoneComClient::OauthClientsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OauthClientsApi' do
  before do
    # run before each test
    @instance = PhoneComClient::OauthClientsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OauthClientsApi' do
    it 'should create an instance of OauthClientsApi' do
      expect(@instance).to be_instance_of(PhoneComClient::OauthClientsApi)
    end
  end

  # unit tests for delete_account_oauth_client
  # Delete an individual OAuth client.
  # Delete an individual OAuth client. See Account OAuth Clients for more info on the properties.
  # @param account_id Account ID
  # @param client_id Client ID
  # @param [Hash] opts the optional parameters
  # @return [DeleteEntry]
  describe 'delete_account_oauth_client test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_account_oauth_client
  # Show details of an individual OAuth client.
  # Show details of an individual OAuth client. See Account OAuth Clients for more info on the properties.
  # @param account_id Account ID
  # @param client_id Client ID
  # @param [Hash] opts the optional parameters
  # @return [OauthClientFull]
  describe 'get_account_oauth_client test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_account_oauth_clients
  # Get a list of OAuth clients for an account.
  # Get a list of OAuth clients for an account. See Account OAuth Clients for more info on the properties.
  # @param account_id Account ID
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :filters_id ID filter
  # @option opts [String] :sort_id ID sorting
  # @option opts [Integer] :limit Max results
  # @option opts [Integer] :offset Results to skip
  # @option opts [String] :fields Field set
  # @return [ListOauthClients]
  describe 'list_account_oauth_clients test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
