=begin
#Phone.com API

#This is a Phone.com api PhoneCom definition

OpenAPI spec version: 1.0.0
Contact: apisupport@phone.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
PhoneCom Codegen version: 2.4.4

=end

require 'spec_helper'
require 'json'

# Unit tests for PhoneComClient::QueuesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'QueuesApi' do
  before do
    # run before each test
    @instance = PhoneComClient::QueuesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of QueuesApi' do
    it 'should create an instance of QueuesApi' do
      expect(@instance).to be_instance_of(PhoneComClient::QueuesApi)
    end
  end

  # unit tests for create_account_queue
  # Create a queue.
  # Create a queue. See Account Queues for more info on the properties.
  # @param account_id Account ID
  # @param [Hash] opts the optional parameters
  # @option opts [CreateQueueParams] :data Queue data
  # @return [QueueFull]
  describe 'create_account_queue test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_account_queue
  # Delete a queue.
  # Delete a queue. See Account Queues for more info on the properties.
  # @param account_id Account ID
  # @param queue_id Queue ID
  # @param [Hash] opts the optional parameters
  # @return [DeleteEntry]
  describe 'delete_account_queue test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_account_queue
  # Show details of an individual queue.
  # Show details of an individual queue. See Account Queues for more info on the properties.
  # @param account_id Account ID
  # @param queue_id Queue ID
  # @param [Hash] opts the optional parameters
  # @return [QueueFull]
  describe 'get_account_queue test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_account_queues
  # Get a list of queues for an account.
  # Get a list of queues for an account. See Account Queues for more info on the properties.
  # @param account_id Account ID
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :filters_id ID filter
  # @option opts [Array<String>] :filters_name Name filter
  # @option opts [String] :sort_id ID sorting
  # @option opts [String] :sort_name Name sorting
  # @option opts [Integer] :limit Max results
  # @option opts [Integer] :offset Results to skip
  # @option opts [String] :fields Field set
  # @return [ListQueues]
  describe 'list_account_queues test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replace_account_queue
  # Replace a queue.
  # Replace a queue. See Account Queues for more info on the properties.
  # @param account_id Account ID
  # @param queue_id Queue ID
  # @param [Hash] opts the optional parameters
  # @option opts [CreateQueueParams] :data Queue data
  # @return [QueueFull]
  describe 'replace_account_queue test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
