=begin
#Phone.com API

#This is a Phone.com api PhoneCom definition

OpenAPI spec version: 1.0.0
Contact: apisupport@phone.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
PhoneCom Codegen version: 2.4.4

=end

require 'spec_helper'
require 'json'

# Unit tests for PhoneComClient::SmsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SmsApi' do
  before do
    # run before each test
    @instance = PhoneComClient::SmsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SmsApi' do
    it 'should create an instance of SmsApi' do
      expect(@instance).to be_instance_of(PhoneComClient::SmsApi)
    end
  end

  # unit tests for create_account_sms
  # Send a SMS to one or a group of recipients.
  # Send a SMS to one or a group of recipients. For details on the input fields, see Intro to SMS. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level Create SMS API with the following definition: POST https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/sms
  # @param account_id Account ID
  # @param data SMS data
  # @param [Hash] opts the optional parameters
  # @return [SmsFull]
  describe 'create_account_sms test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_account_sms
  # This service shows the details of an individual SMS.
  # This service shows the details of an individual SMS. See Intro to SMS for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level Get SMS API with the following definition: GET https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/sms/:sms_id
  # @param account_id Account ID
  # @param sms_id SMS ID
  # @param [Hash] opts the optional parameters
  # @return [SmsFull]
  describe 'get_account_sms test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_account_sms
  # Get a list of SMS messages for an account.
  # Get a list of SMS messages for an account. See Intro to SMS for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level List SMS API with the following definition: GET https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/sms
  # @param account_id Account ID
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :filters_id ID filter
  # @option opts [String] :filters_from Caller ID filter
  # @option opts [String] :filters_to Callee ID filter, the E.164 phone number to send the SMS TO. Note you must encode the + as %2B
  # @option opts [String] :filters_direction Direction filter
  # @option opts [Array<String>] :filters_extension Extension filter
  # @option opts [String] :filters_created_at Date string representing the UTC time that sms was created
  # @option opts [String] :sort_id ID sorting
  # @option opts [String] :sort_created_at Sort by created time of message
  # @option opts [Integer] :limit Max results
  # @option opts [Integer] :offset Results to skip
  # @option opts [String] :fields Field set
  # @return [ListSms]
  describe 'list_account_sms test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_account_sms
  # Update the is_new parameter in a sms record.
  # Update the is_new parameter in a sms record. See Account SMS for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level Patch SMS API with the following definition: PATCH https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/sms/:sms_id
  # @param account_id Account ID
  # @param sms_id SMS ID
  # @param [Hash] opts the optional parameters
  # @option opts [PatchSmsParams] :data Sms data
  # @return [SmsFull]
  describe 'patch_account_sms test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
